name: Testing on Ubuntu

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7']
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - ruby-version: head
            os: ubuntu-latest
            experimental: true
# FIXME: on GitHub action, when cpufreq is not available by default
#        capability: [true, false]
        capability: [false]

    name: Ruby ${{ matrix.ruby-version }} capability ${{ matrix.capability }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Ruby
        uses: ruby/setup-ruby@a6b46b8a08edb18935835849f2a17072d5cc8c73 # v1.192.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install libcap-ng-dev
          gem install bundler -v 2.2.27
          bundle _2.2.27_ install
      - name: setup linux capability (cap_dac_read_search=+eip)
        run: sudo setcap cap_dac_read_search=+eip $(command -v ruby)
        if: ${{ matrix.capability }}
      - name: show linux capability
        run: sudo getcap $(command -v ruby)
      - name: Run tests
        run: bundle exec rake test
