name: Testing on Ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '2.7', '2.6']
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - ruby-version: head
            os: ubuntu-latest
            experimental: true
        capability: [true, false]

    name: Unit testing with Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install libcap-ng-dev
          bundle install
      - name: setup linux capability (cap_dac_read_search=+eip)
        run: sudo setcap cap_dac_read_search=+eip $(command -v ruby)
        if: ${{ matrix.capability }} == true }}
      - name: show linux capability (cap_dac_read_search=+eip)
        run: sudo getcap $(command -v ruby)
      - name: Run tests
        run: bundle exec rake test
